### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vcraescu** [Studio-42/elFinder#2070]
`jquery.js:357 Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.camelCase (https://bv.dev/assets/jquery/jquery.js:357:17)
    at Function.css (https://bv.dev/assets/jquery/jquery.js:7155:22)
    at Object.get (https://bv.dev/assets/jquery/jquery.js:7196:38)
    at Function.css (https://bv.dev/assets/jquery/jquery.js:7167:16)
    at https://bv.dev/assets/jquery/jquery.js:10918:13
    at access (https://bv.dev/assets/jquery/jquery.js:4428:13)
    at jQuery.fn.init.jQuery.fn.(anonymous function) [as height] (https://bv.dev/assets/jquery/jquery.js:10889:11)
    at HTMLDivElement.<anonymous> (https://bv.dev/assets/elfinder/dist/js/elfinder.min.js:13:7168)
    at HTMLDivElement.dispatch (https://bv.dev/assets/jquery/jquery.js:5226:27)`

<img width="881" alt="screen shot 2017-06-26 at 14 48 41" src="https://user-images.githubusercontent.com/941660/27537952-a097f268-5a7e-11e7-8a0c-7117676f5e70.png">

The above error happens every time you resize the elfinder window.

This happens on >=2.1.5 (at least that's what I tested so far). On latest version, because of this error nothing is displayed in file manager and makes the entire app unusable. I had to downgrade it to 2.1.5 which throws the error but at least it function properly afterwards.

**Comment by nao-pon** [comment]
@vcraescu This problem may be solved with 41e9d9acfb8a09c1765d1c7dad6f31a9c670b9eb, what about with [nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip)?

**Comment by vcraescu** [comment]
@nao-pon I haven't tried yet.

**Comment by nao-pon** [comment]
Would you try the nightly build?

**Comment by vcraescu** [comment]
@nao-pon The nightly build works perfectly! The window is not being sluggish when is resized. So your changes properly fix the issue. When it's gonna be released under 2.1.25?

**Comment by nao-pon** [comment]
@vcraescu Thank you for checking! This fix will be included in the next release 2.1.26.
